#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
mkdir -p "$SCRIPT_DIR/build"
protoc \
  --plugin=protoc-gen-js="$SCRIPT_DIR/../protoc/bin.mjs" \
  --js_out="$SCRIPT_DIR/./build" \
  -I "$SCRIPT_DIR/../../vega/protos/sources" \
  vega/commands/v1/transaction.proto
