#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mkdir -p "$SCRIPT_DIR/build"
protoc \
  --plugin=protoc-gen-js="$SCRIPT_DIR/../protoc/bin.js" \
  --js_out="$SCRIPT_DIR/./build" \
  -I "$SCRIPT_DIR/fixtures" \
  core.proto enum.proto nested.proto recursive.proto shadow.proto

# Top-level module is ESM but compiled files are CommonJS
echo '{"type":"commonjs"}' > "$SCRIPT_DIR/build/package.json"
