import join from '../../../utils/join.js'
import { relative } from 'path'

export default function ({ path, message, encodeFile, decodeFile, nestedEnums, nestedMessages }) {
  return join`
    /// autogenerated by protoc-plugin-js

    module.exports = {
     ...require('./${relative(path, encodeFile.path)}'),
      ...require('./${relative(path, decodeFile.path)}'),
      ${[
      ...nestedEnums.map(n => `'${n.identifier}': require('./${relative(path, n.path)}')`),
      ...nestedMessages.map(n => `'${n.identifier}': require('./${relative(path, n.path)}')`)
    ].join(',\n')}
    }
  `
}
